name: Release

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Dry run release (do not Publish)"
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-22.04
    name: Release
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 22

      - run: npm ci
      - run: npm run build -ws
      - run: npm run test -ws

      - name: auth npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: run semantic-release
        run: |
          if [ "${{ inputs.dry_run }}" = "true" ]; then
            npx semantic-release --dry-run
          else
            npx semantic-release
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
