name: Release

on:
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  publish:
    # ubuntu 24 is queued for way too long
    # https://docs.npmjs.com/trusted-publishers
    # https://github.com/npm/cli/issues/8730
    # https://github.com/idempot-dev/idempot-js/pull/54
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          # https://github.com/npm/cli/issues/9088
          node-version: '24'

      - run: npm ci
      - run: npm run build -ws
      - run: npm run test -ws

      # todo : switch to multi-semantic-release
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # this cannot be executed within semantic-release exec
      # it is using the wrong npm version
      - run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            npm publish -ws --provenance --access public
          else
            npm publish -ws --provenance --access public --tag canary
          fi
        env:
          NPM_CONFIG_PROVENANCE: true
